
### get all users
GET http://localhost:3000

### get one user by id
GET http://localhost:3000/routes/users/621d882b58ee3ba61cffc6cd

### add user
POST http://localhost:3000/routes/users
Content-Type: application/json

{
    "name": "qwe",
    "surname": "asd",
    "email": "qweqwe@cmvcv.com",
    "phone": "+79456134567"
}

### update user
PATCH http://localhost:3000/routes/users/621d882b58ee3ba61cffc6cd
Content-Type: application/json

{        
    "surname": "Taylan"
}

### Delete user
DELETE http://localhost:3000/routes/users/621d885158ee3ba61cffc6cf


###################AIRCRAFTS#########################################

### get all Aircarfts
GET http://localhost:3000/aircrafts

### get one Aircarft by id
GET http://localhost:3000/aircrafts/621da41bf6d98edf8fda3776

###
GET http://localhost:3000/aircrafts?wing_span[gt]=40


###
GET http://localhost:3000/aircrafts?wing_span[gt]=40